Questionnarie/Models/TaskSummaryViewModel.cs
using Tasks.Model;
using Tasks.Model.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tasks.Models
{
    public class TaskSummaryViewModel
    {
        public UserRoleEnum Role { get; set; }
        public WorkTask Task { get; set; }
    }
}

Questionnarie/Controllers/AuthController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Tasks.Model;
using Tasks.Model.Abstract;
using Tasks.Models;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Linq;
using System.Security.Cryptography;
using Tasks.Helpers;
using Tasks.Abstract;

namespace Tasks.Controllers
{
    [AllowAnonymous]
    public class AuthController : Controller
    {
        private IUserTasksRepository _userRepository;
        private IEmailSender _mailSender;
        private IAppSettings _appSettings;

        public AuthController(IUserTasksRepository userRepository, IEmailSender mailSender, IAppSettings appSettings)
        {
            _userRepository = userRepository;
            _mailSender = mailSender;
            _appSettings = appSettings;
        }

        // GET: Auth
        public ActionResult Login(string returnUrl)
        {
            LoginViewModel vm = new LoginViewModel() { ReturnUrl = returnUrl };
            return View(vm);
        }

        // POST: Auth
        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            //получение user из базы
            User user = _userRepository.GetUser(model.UserName, model.Password);
            
            if(user == null)
            {
                //пользоватлель в БД не найден
                ModelState.AddModelError("", "Invalid user name or password!");
                return View(model);
            }

            //создание объекта хранящего в себе информацию о пользователе
            AppUserState appUserState = new AppUserState()
            {
                UserName = user.UserName,
                Role = user.RoleString
            };

            //авторизация
            IdentitySignin(appUserState);

            if (!string.IsNullOrEmpty(model.ReturnUrl))
                //если пользователь хотел открыть какую-то страницу и она не открылась
                //из-за того, что он был не авторизован, вернуть ее.
                return Redirect(model.ReturnUrl);

            //в противном случае вернуть список задач, это view по умолчанию
            return Redirect(Url.Action("TaskList", "Home"));
        }

        public ViewResult Logout() {
            IdentitySignOut();
            return View();
        }

        public ViewResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public ViewResult ForgotPassword(ForgotPasswordViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            //e-mail точно не пустой
            IEnumerable<User> emailUsers = _userRepository.GetUserByEmail(model.Email);

            if (emailUsers.Count() > 1)
            {
                TempData["Error"]="More than one user exists with this email!";
                return View();
            }

            //найден один пользователь с таким e-mail
            // сохраняем его
            User user = emailUsers.First();

            string tokenStr = GenerateRandomToken();
            //сохраняем токен в базе
            user.PasswordResetToken = tokenStr;
            user.PasswordResetTokenDate = DateTime.Now;

            _userRepository.Save();
            // и в ссылке пользователю
            string callbackUrl = $"{Request.Url.Scheme}://{Request.Url.Authority}{Url.Content(Url.Action("ChangePassword", new { token = tokenStr, userId = user.UserName }))}";
            string mailBody = String.Format("Please reset your password by clicking <a href='" + callbackUrl + "'>here</a>");
            _mailSender.SendEmail(user.Email, "Task4u: Reset Password", mailBody);

            return View("ResetEmailIsSent");
        }

        public ActionResult ChangePassword(string token, string userid)
        {
            User user = _userRepository.GetUserByToken(userid, token);
            if (user==null || 
                DateTime.Now.Subtract(user.PasswordResetTokenDate.Value).TotalSeconds > 
                    _appSettings.ResetPasswordTokenExpireTime)
            {
                return HttpNotFound();
            }
            ChangePasswordViewModel vm = new ChangePasswordViewModel() { Token = token, UserId = userid };

            return View(vm);
        }

        [HttpPost]
        public ActionResult ChangePassword(string token, string userid, string newPwd)
        {
            User user = _userRepository.GetUserByToken(userid, token);
            if (user == null ||
                DateTime.Now.Subtract(user.PasswordResetTokenDate.Value).TotalSeconds >
                    _appSettings.ResetPasswordTokenExpireTime)
            {
                return HttpNotFound();
            }

            user.Password = newPwd;
            user.PasswordResetToken = null;
            user.PasswordResetTokenDate = null;
            _userRepository.Save();

            return View("ChangePwdSuccess");
        }
        private string GenerateRandomToken()
        {
            String result;
            using (RandomNumberGenerator rng = RandomNumberGenerator.Create())
            {

                Byte[] bytes = new Byte[10];
                rng.GetBytes(bytes);

                result = Convert.ToBase64String(bytes);
            }

            return result;
        }
        private void IdentitySignin (AppUserState appUserState, bool isPesistent =false)
        {
            List<Claim> claims = new List<Claim>();

            //create required claims
            //claims.Add(new Claim(ClaimTypes.NameIdentifier, appUserState.UserId));
            string[] roles = appUserState.Role.Split(';');
            claims.Add(new Claim(ClaimTypes.Name, appUserState.UserName));
            foreach (string r in roles)
            {
                claims.Add(new Claim(ClaimTypes.Role, r));
            }
            ClaimsIdentity identity = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);

            AuthenticationManager.SignIn(new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = isPesistent,
                ExpiresUtc = DateTime.UtcNow.AddMinutes(30)
            }, identity);
            
        }

        private void IdentitySignOut()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
        }

        private IAuthenticationManager AuthenticationManager {
            get { return HttpContext.GetOwinContext().Authentication; }
        }
    }
}

Questionnarie/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tasks.Constants;

namespace Tasks.Controllers
{
    public class NavController : Controller
    {
        public PartialViewResult Menu(MenuEnum selection = MenuEnum.TasksAssignedToMe, bool horizontalLayout =false)
        {
            ViewBag.Selection = selection;
            IEnumerable<MenuEnum> selections = new MenuEnum[] { MenuEnum.TasksAssignedToMe, MenuEnum.MyCompletedTasks, MenuEnum.MyActiveTasks, MenuEnum.MyArchiveTasks};
            string viewName = horizontalLayout ? "MenuHorizontal" : "Menu";
            return PartialView(viewName,selections);
        }
    }
}

Questionnarie/Views/Shared/CompletionDialog.cshtml
@model Tasks.Models.CompleteDialogViewModel

@{ 
    Layout = null;
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(x=>x.TaskId)

    <div class="form-group">
        @Html.LabelFor(x => x.CompleteMsg)
        @Html.TextAreaFor(x => x.CompleteMsg, new { @class = "form-control" })
    </div>
    <input class="btn btn-primary" type="submit" value="Save" />
    @Html.ActionLink("Return to task list", "TaskList", "Home", new { @class = "btn btn-default" })
}

Questionnarie/Views/Shared/TaskSummary.cshtml
@model Tasks.Models.TaskSummaryViewModel

@*<div class="well" style="overflow:auto;">
    <span class="pull-left label label-default">Task from: @Model.Task.FromUserId</span>
    @if (Model.Task.Completed)
    {
        <span class="pull-right label label-success">Task completed</span>
    }
    
    <h4 class="visible-xs">
        <strong>@Model.Task.Summary</strong>
        <span class="pull-right label label-primary">@Model.Task.When.ToString("dd/MM/yyyy")</span>
    </h4>

    <h3 class="hidden-xs">
        <strong>@Model.Task.Summary</strong>
        <span class="pull-right label label-primary">Due to @Model.Task.When.ToString("dd/MM/yyyy")</span>
    </h3>

    <span class="lead">@Model.Task.Subject</span>
    <span class="pull-right">
        @if (!Model.Task.Completed)
        {
            <button class="btn btn-success" onclick="DisplayUpdateCustomerDialog(@Model.Task.TaskId)">Complete Task</button>
        }
        else
        {
            <button class="btn btn-warning" onclick="DisplayUpdateCustomerDialog(@Model.Task.TaskId)">Show Messages</button>
        }
    </span>
</div>*@

<div class="well" style="overflow:auto;">
    @if (Model.Task.Completed)
    {
        <h3 class="text-center">
            <span class="label label-success">Task completed</span>
        </h3>
    }
    <div class="col-xs-8">
        <span class="label label-default">Task from: @Model.Task.FromUserId</span>
        <h4 class="visible-xs">
            <strong>@Model.Task.Subject</strong>
        </h4>

        <h3 class="hidden-xs">
            <strong>@Model.Task.Subject</strong>
        </h3>

        <span class="lead">@Model.Task.Summary</span>

    </div>
    <div class="pull-right col-xs-4">


        <h3 class="hidden-xs">
            <span class="label label-primary">Due to @Model.Task.When.ToString("dd/MM/yyyy")</span>
        </h3>
        <h4 class="visible-xs">
            <span class="label label-primary">@Model.Task.When.ToString("dd/MM/yyyy")</span>
        </h4>


        @*@Html.ActionLink("Complete Task", actionName: "CompleteTask", controllerName: "Task", routeValues: new { taskid = Model.Task.TaskId },
            htmlAttributes: new { @class = "btn btn-success" })*@
        @if (!Model.Task.Completed)
        {
            <button class="btn btn-success" onclick="DisplayUpdateCustomerDialog(@Model.Task.TaskId)">Complete Task</button>
        }
        else
        {
            <button class="btn btn-warning" onclick="DisplayUpdateCustomerDialog(@Model.Task.TaskId)">Show Messages</button>
        }
    </div>


</div>

Questionnarie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tasks", "TaskList", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Logout", "Auth")">
                            <span class="glyphicon glyphicon-log-out"></span> 
                            Logout
                        </a>
                    </li>
                    @if (User.IsInRole(Tasks.Model.UserRoleEnum.TaskMaker.ToString()))
                    {
                    <li>
                        <a href="@Url.Action("NewTask", "Task")">
                            <span class="glyphicon glyphicon-new-window"></span> New Task
                        </a>
                    </li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class=" ">
        <div class="visible-xs">
            @Html.Action("Menu", "Nav", new { horizontalLayout = true })
        </div>
        <div id="categories" class="col-xs-3 hidden-xs">
            @Html.Action("Menu","Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>

</body>
</html>

Questionnarie/Views/Shared/_LogInOutLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tasks", "TaskList", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class=" ">
        <div id="categories" class="col-xs-3">
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>